#Created by webjeda - http://webjeda.com

title: acad√© #Keep it short
subtitle: Joel Gronfier
email: contact@acade.fr


baseurl: /bheema

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
